### ISSUE TITLE
Teach AI to build bunkers near the border

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#16]

**Comment by bvanevery** [comment]
You disabled bunkers.  You can close this.

**Comment by tnevolin** [comment]
That is right but I plan to enable them as soon as I teach AI to use them!
😁

This is a reminder for myself to do that.

**Comment by bvanevery** [comment]
Beg pardon but you need to learn to walk before you can fly.  The AI isn't even competent at bringing the fight to the enemy, or even producing defensive forces.  Design-wise, this is a complete waste of time.  It was a bad design in the original game, due to the AI's incompetence in the original game.  And you are in no better position, to put this right, at present.

I've been living without bunkers for almost the entire existence of my mod.  You don't need that POS.  It's a leftover from nutty Civ II nonsense.  Ditch it.  Save yourself the work, forever.

Do you really want to write tactical logic about "oh, my hovertank has some moves left, but if I arrive at an enemy bunker, I have to stop as it gets captured..."  Complete waste of time.

**Comment by tnevolin** [comment]
I sure need to learn small things first. That is not a reason to close this one as it is too far fetched. Or do you think I should close it for the time being to not hang there forever?

So you are thinking bunkers are just not interesting part of the game overall?

**Comment by bvanevery** [comment]
Do not pollute your TODO list with picky nonsense that you're unlikely to ever get to in the real world.  You've got it in your bug tracker.  You personally will remember that it's there.  Or if you don't, IMNSHO, _no loss_.  But you probably will remember.  Meanwhile, you don't need to be broadcasting to the world any Issues that aren't likely ever going to be dealt with.  Makes you look like you don't take care of stuff, especially as Issues get older and older without being dealt with.

The bunkers are a stupid uninterestring part of the game, only in there because they made Civ II first.  Combat is _not_ better for having them.  It's like the "well I don't want to deal with splash damage" feature.  Here's a clue: Civ V went to 1 unit per hex only.  Commercial practice went to anti-stack.  Maybe a little too extremely, but bunkers are pro-stack.  Dig in, advance, dig in, advance, done that BS in plenty of other games.

**Comment by tnevolin** [comment]
Good point. Closing it.
