### ISSUE TITLE
Enforce SE choice preference for AI factions

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/thinker-doer#21]
Thinker seems to override it freely.

Here is the example.
http://alphacentauri2.info/index.php?topic=21359.msg127897#msg127897

**Comment by nevill-spb** [comment]
I'd rather see them weighed, not enforced. Thinker SE choices are a lot more sensible than vanilla. I forgot how long it was since I last saw AI run Wealth instead of Power.

I still don't see it often, even though it's one of the more powerful settings. Apparently the AIs are at war all the time, and it makes them run FUNDY+POWER more often then not.

**Comment by tnevolin** [comment]
That was instigated by bvanavery as he didn't like computer factions deviate from their designated choice. So weighting it won't help. Some faction has to stick to some choices they mentioning in text. So either that or this task won't need to be implemented at all.
😞
It's a political discussion I don't have preference about. It will be equally good for me either way.

**Comment by tnevolin** [comment]
#181

**Comment by bvanevery** [comment]
Domai's not obeying.  He went Cybernetic and then Thought Control.  See #52

**Comment by tnevolin** [comment]
That is fixed there.
