### ISSUE TITLE
Ability costs

### ISSUE THREAD

**Issue by nevill-spb** [tnevolin/thinker-doer#23]
Continuing the trend of "making WtP complonents optional" I'd like to request a partial restoration of an old behavior.

Specifically, the ability costs. One of the most-used cost factors was -1, or attack/defense ratio, making certain abilities free for pure defense units, and less costly for balanced ones. I find that an extra row is a poor substitute for that.

Another cost factors that I found quite useful were
;          -4 = Increases w/ speed value
;          010000000000 = Cost increased for land units
The new scheme completely ignores those, making it impossible to create abilities that would be free for air/sea units, but not for land ones, or the ones that scale their costs with speed.

Cost factors 3-4 (75%-100% increase in costs), as well as +3-4 rows are not really used, so if you can have a limited number of cost options, I'd much rather have those restored.

Is it possible to have them back?

**Comment by tnevolin** [comment]
Which ones do you have in mind?

**Comment by nevill-spb** [comment]
I listed the options I'd like to have restored. If you are asking what abilities I want priced that way, well, I want these for my mod (which mostly keeps the gameplay as it was in vanilla while trying to avoid the most egregious exploits):

Clean reactors at -1 (attack/def). Free for defensive units, not so much for formers and attackers.
Put trance back at -1. Maybe?
ECM belongs to -1 as well, I think. Perhaps AAA too.
Make Deep Radar cost something for land units.
Make air superiority free for air units, but not land ones.

**Comment by tnevolin** [comment]
1. Apparently, since I overrode unit cost calculation I need to reintroduce these negative there. Let me work on this first.

2. I agree abilities may benefit from further differentiation. However, I found these ratio options too coarse grained and difficult to customize with. All these rounding and other problems. See below.
I would suggest to think first what changes you want to make and then apply them as you see they should instead of thinking which one broken negative category it belongs.

3. Specific changes

Clean reactors at -1 (attack/def). Free for defensive units, not so much for formers and attackers.
I like the free police idea. However, that makes all mixed attackers units (armor >= weapon) also free. Wouldn't it be a too much of a giveaway?

Put trance back at -1. Maybe?
I'll be 0 for all pure defenders and also 0 for Scout Patrol since 25% increase of 1 rounded = 0. Is this what you had in mind?
Currently it costs just 1 row of minerals which is not that much for this ability. You'll spend more on maintenance.

ECM belongs to -1 as well, I think. Perhaps AAA too.
These abilities are for defensive units mostly. Make them free? This would seriously shift balance toward defense which is already quite strong. That would cause whole fast and air attackers balance review.
Again, rounding issues. AAA would cost 25% for 8-8-1 but zero for 8-10-1. One would be tempted to add this extra layer of defense to save on 25% cost increase.

Make Deep Radar cost something for land units.
It is still like that. I never changed it.

Make air superiority free for air units, but not land ones.
I can make it work same as Deep Radar - free for air/sea and 1 for land.

**Comment by tnevolin** [comment]
Partially done in #165.
Trance and ECM need further discussion.
