### ISSUE TITLE
Fanatic Attack bonus is overpowered

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#56]
+50% is grossly excessive.  If the Believers actually need that kind of bonus to make them a viable faction, then there's something seriously wrong with their play balance.  That would be like having more than +3 PLANET bonus that works on all units, not just psi combat.

The stock game and my mod do +25%.

**Comment by tnevolin** [comment]
Well, I felt sorry for them as they essentially cannot do anything else but fighting. If they won't be able to do it successfully they die. And they also won't have a research edge in super advanced weaponry. This bonus is sort of compensates for obsolete units and allow to use them somewhat effectively.
They do fine in vanilla due to very delayed defense development for everybody + multi round combat that give strong odd skew for even slight advantage. It WTP their life is tougher.
But if you say this is too much, I don't mind.

> That would be like having more than +3 PLANET bonus that works on all units, not just psi combat.
It's a stretch. It's only offense bonus and only for non psi combat. In your terms it is less than half of what you stated. Probably somewhere 1.0-1.2 PLANET on average. Providing psi defense is a common strategy they are pretty easy stoppable with their negative PLANET rating.

**Comment by bvanevery** [comment]
You don't have to have the Believers have a negative PLANET rating.  It's a complete throwaway, this idea that Miriam is hostile to Planet.  There's not a single video or quote to support the idea, at all.  Only this 1 line in the faction file.  It's basically out of character.  Miriam's thing is to prattle on about God, and to be opposed by Yang and Zhakarov who are atheists.  Nothing to do at Planet at all.  There's not a single instance of Miriam vs. Deidre interaction in the whole game.

**Comment by tnevolin** [comment]
I don't mind removing this penalty from them either.
My point was about their offence bonus, though. It may be strong but it is very limited and they have to attack to use it. AI does not seem to dominate with this bonus. Same for player. Try to play them few games and win every time. That would undoubtfully prove this is OP.

**Comment by bvanevery** [comment]
Well, the general problem with your WTP defense stuff is you're in a serious cascade climb of overinflated modifiers.  Your territory bonus is ridiculously high, that's the main problem.  So that's why you think another +50% attack is no big whoop, because you've got defense dialed up way too much.  Scouts shouldn't be good defenders against Chaos guns.  I'm not sure how problematic it is now in more recent releases, as you can tell from my playtests that I simply won't use your territorial defense bonuses as is.  To me this is like cleaning out a carburetor that's got too much soot in it.  +50% attack is clearly way too high, an overcompensation for some other problem.  I think I know what most of the problems are, I'm just filing Issues one at a time, to keep focus.
