### ISSUE TITLE
AIs buying cities and all units in/around it with probes non-stop is game-breaking

### ISSUE THREAD

**Issue by afwbkbc** [tnevolin/thinker-doer#76]
Consider this game I played yesterday - https://www.youtube.com/watch?v=XPH0-oMPmBk , it went all fine and all, except for probes. For some reason it is ridiculously easy/cheap for AIs to just go and mind control every city, so big part of my strategy was to NEVER EVER allow any probe into city (that was annoying but ok).
As you see after ~07:45:00 I failed to do that ONCE, and it costed me entire army and entire game since I would not be able to defend against my former army in time and it would snowball over me (I have no idea how cheap it all was since Roze still got tons of energy available the next turn). Yes it's Transcend difficulty, but still it shouldn't be game over from just one probe in right place at right time.
The cost of mind controling cities does not depend on units stationed there and around, right? So as long as one has enough credits for city he will get all units in it for free? This needs to be fixed, cost of units must be included aswell. So cities with big armies stationed in them should be much more expensive (if possible at all) to just mind control.
'one probe went through' shouldn't be a matter of life and death.

**Comment by tnevolin** [comment]
First of all, kudos to you for recording the **whole** game! Incredible. Do you record all of your games just in case?
Also a save game before your base was mind controlled would be interesting to look at just from educational perspective.

As far as I understand, the number of units in base is a factor to mind control cost. See [here](https://apolyton.net/forum/other-games/alpha-centauri/147933-how-to-calculate-the-cost-of-city-mind-control/page2?viewfull=1#post5248869).

They probably got it cheap anyway because it was close to their HQ. That is the major factor too.

**Comment by afwbkbc** [comment]
Oh, I didn't save there unfortunately, I like to play as in 'ironman mode' (every decision final) so autosaves were off aswell, but I'll enable them for next games (and yes I record them just in case).
Still, close to HQ or not, this is big problem as now it's super risky to station army in newly captured cities (!!!), which is counter-intuitive and unrealistic.
So now when I capture cities I leave them without defence and try to build Infantry Probe Team before moving ANY unit there, otherwise I'll risk my army a lot (because Transcend AI doesn't get short on energy reserves and can mind control every city as long as probe can get there), I don't think this is how war should be carried on tbh.
Even if we compare risks from probe with those of planet buster - probe can be more dangerous because it not only takes away your city but can steal your army there aswell and use it against you.

**Comment by tnevolin** [comment]
> can mind control every city as long as probe can get there

I doubt that. MC cost increases every time it is executed. So there is a reasonable limit on how many bases faction can MC during the game. Beyond that this becomes too expensive. You may notice that if you actually allowed them to MC bases back. First one or two are very easy for them but at some point they slow down and don't do this anymore.

**Comment by tnevolin** [comment]
Here. Look at that.
https://alphacentauri2.info/wiki/Mind_Control_Cost

There are plenty of means to increase MC cost including stuffing base with polymorphic encryption units and assault units. That not even mentioning raising your PROBE rating to increase and potentially prevent MC. You just need to add these tricks to your strategy mix. SMACX is a very feature reach game with multiple ways to solve problems. An army composed solely from pure assault units is not an answer to everything.

**Comment by afwbkbc** [comment]
Maybe problem exists only on Transcend difficulty, where AIs get huge bonuses and never run out of energy, but so far I barely saw probe getting to my city and NOT mind-controlling it, maybe once or twice at most.
Still, probe is ultimate strongest and most dangerous unit ever (both in Vanilla and now, but now AI use them more so problem intensified).

**Comment by tnevolin** [comment]
First, I challenge you to actually test it. Play against AI and let them to buy bases back. You can use precautions to save big part of your army by retracting them before that happens but don't kill probes and don't prevent them from MC. You can do this in editing mode and give yourself plenty of army so you keep capturing and losing bases. How much time per game they were able to do it until they run out of money?

Second, if this happens on highest difficulty only than this is as designed. Highest level is supposed to be quite challenging even for seasoned players. That is what Thinker/WTP is working on. Do not derail our efforts just because you got used to beat toothless vanilla AI on highest difficulty every time. That should **not** be like that.

Third, what do you propose to change if anything? Disable this feature? Make it more expensive (= effectively disable)? I don't think we can tone it down to avoid player losing their whole army disregarding MC possibility. One **can** engineer the case to lose the army. I believe this feature should exist as an alternative to conventional combat as many other alternatives in the game. That what makes it so playable.
If they are so powerful - use them too! Why don't you?

I am planning to adjust the MC cost formula to include units adjacent to base as they are subverted too. That would increase cost and eventually reducing number of MCs AI can perform.

**Comment by afwbkbc** [comment]
Just had another game that quickly went to 'catch the probe' tag - AI built military units too, but they were just trash and cannon fodder, but it kept spamming probes until one of them went through and bought my entire army.
Literally whole game turns around probes, this isn't fun tbh. Strongest defence is NOTHING if one probe sneaks through (all AI needs to do is spam larger pack of probes and rush the city). The only defense against it is stacking 5-10 probes into every city, yes sometimes it's possible to intercept them but not in every case (for example this time city was on river so AI's probes could just reach it in one turn in whatever quantities they built them).
It's not fun where probes become the main and only concern in game.

> Highest level is supposed to be quite challenging even for seasoned players

yes, but if 'challenge' is created from AI spamming probes non-stop and you lose when one gets through it's not fun anymore.

**Comment by tnevolin** [comment]
I agree that is a concern.  Are you playing version with modified MC cost? How many bases did they buy from you already? Do you have a save? Did you yourself tried to buy enemy bases? Did you find cost reasonable?

How do you think this can be dealt with? Raise cost some more?

**Comment by afwbkbc** [comment]
> Are you playing version with modified MC cost?

Wdym? Just normal version of mod (only changing random modifier from 2.0 to 1.0).

> How many bases did they buy from you already?

It was first one that game, but they got 90% of my army and also that base had roads to multiple others so I imagine probes would just rush onto them. In previous games they kept buying every city they could reach (not that hard to imagine that Transcend AI's bonuses allow to have infinite buying power at mid-game or later).

> Do you have a save?

Ah, no, sorry. I'll make it next game.

> Did you yourself tried to buy enemy bases?

In that game - no, in previous I tried but cost was above 1500 and sometimes above 3000 credits for average city (and I had +2 PROBE).

> Did you find cost reasonable?

For players - yes, I imagine it's problem when dealing with Transcend AI since they have (nearly?) unlimited buying power (do they also get discounts on mind control costs?).

> How do you think this can be dealt with? Raise cost some more?

Hmm, now that is a good question. Raising costs would impair players (leaving mind control unavailable to them completely).
I think good solution would be to make cost increase exponentially with number of combat units stationed there (so base with 5+ units would be VERY expensive and 10-20 units completely unbuyable), that would still allow probes to capture small cities on the sides but will prevent whole army purchasing (and insta-winning).
Exact formula, well, I don't know how it currently works but maybe something like this:
(cost_of_city_based_on_buildings_distances_and_stuff + (cost_of_mind_controlling_all_stationed_units_together * count_of_stationed_units)) * PROBE_and_other_modifiers_and_stuff
the important change is multiplying by count_of_stationed_units, so the more units are kept there the higher price will go up for every one of them, so cities with big armies will be immune to mind control as long as army is stationed there.

**Comment by tnevolin** [comment]
Ah. I see now you are on the older version.
Please upgrade to version 237+ or latest one. It has MC cost specifically tailored based on similar complaints. Please try it and let let know if it solves problem.

Here is the new MC description.
https://github.com/tnevolin/thinker-doer#alternative-subversion-and-mind-control-formulas-and-mechanics

Let me know if it works for you.

You can ping me here or on forum if you still have questions about it.

**Comment by afwbkbc** [comment]
Well, it's still a problem it seems https://www.youtube.com/watch?v=x3WWWVzz2hw
I tried my best to defend cities with probes but at one point of time they killed all probes and after a while bought city with most of my army again.
As usual, it's game over since I was already short on units and every one was precious.

I don't know, maybe just disable 'Mind Control Probe' until we figure out balanced way for it to work? Single probe can ruin game instantly.

**Comment by tnevolin** [comment]
What I did is modified mind control cost **structure** to include values recognized by most players: resource intake, building, projects, and, most importantly, the flat cost of subverted units. Meaning each unit in base or or adjacent to it adds to MC cost exactly the subversion cost. So the more units you have in base the more MC cost.

Now that fixes the structure making it more sane and additive. At the same time actual cost coefficients are subject to adjustment. Please review the modified formula with all parameters and propose your take on that. Then we can test it again and see if it works.

Also if you can post your save here I can verify the formula itself works correct and can tell you how much they spent to MC it.

**Comment by tnevolin** [comment]
Speaking about running out of probes. This is one unit type in your army composition that you should manage. If successful conquest requires outnumbering enemy probes than this is it. Similar complain type can be filed for any other unit required type in your army composition. Like enemy outnumbered me in artillery and knock all my bombardiers out - now they injure my attackers and I cannot capture their bases - let's disable artillery. Or I ran out of protective units and they wiped out my doom stack with few counterattacks - let's disable AI ability to attack my units. Or I didn't prepare enough strong attackers and now I cannot penetrate their defense - let's forbid AI to defend their bases. etc.
😀

**Comment by afwbkbc** [comment]
It is impossible to always outnumber enemy at every unit type, especially on transcend. One of reasons is that you can't know how many of them enemy has (or will build next turn).
So it's normal to sometimes lose some battles, however, in this particular case not having enough probes with your army (and you can't know how many will be 'enough' since you can't see more than several tiles away and on roads enemy probes can run 6 tiles) can mean game over for you because AI will purchase your entire army or big chunk of it.
Tbh, the only reason player can survive vs Transcend AI at all now is that AI sends only 1-2, maximum 3 probes at one base, but nothing prevents him from hoarding some 10 or 20 probes (and then send to same city), in this case it will be impossible to defend against and will be just a matter of time before city with large army gets purchased and it's game over.

Probes in hands of transcend AI have way too much of destructive potential, as I said - it's more destructive than Planet Buster weapons because AI not only takes city away from you but it then uses this city and whatever army was stationed there for himself, easily starting and continuing snowballing.

**Comment by tnevolin** [comment]
I can do a switch to disable it.

However, I personally don't see any problem with it.

1. MC cost includes unit cost. If AI able to buy a base with an army that means it can buy all these units one by one in a field as well.  Having a lot of money and buying stuff is a completely legitimate strategy alternative to brute force. Maybe we just need to increase subversion cost to make it more fair?
2. There are plenty ways to counter MC beside counter probes. Some obvious ones are: raising PROBE rating,  moving HQ close to front line, increase happiness, building COC.
3. Buying bases is a designed counter play against wildly advancing opponent. Elongation from own HQ and previously owned bases reduces MC cost. This is designed **on purpose** to outweigh sheer military power.
4. Losing a base with large army is not losing the game. One just loses a momentum - the feeling of winning. Even in vanilla it is not the end of the world but just temporary setback. Player may need to switch to defense until they accumulate more attackers.
5. Rephrasing the above. WTP/Thinker cancels the notion of "undead army". Units die. One need to have strong economy to fuel conquest. From this point of view losing part of the army for twice as economically stronger player is a temporary slowdown. Their production power does not go anywhere and eventually overwhelms enemy's. From the other side being economically weaker and hoping to lead unstoppable conquest is an illusion. MC or not MC that will not work long term in this mod.

**Comment by tnevolin** [comment]
Can you share your save?

**Comment by afwbkbc** [comment]
>  If AI able to buy a base with an army that means it can buy all these units one by one in a field as well.

In the field only lone units are purchasable, and it looks like it was intentional. Cities, however, can be purchased instantly with everything inside, how does it make sense?

> There are plenty ways to counter MC beside counter probes. Some obvious ones are: raising PROBE rating, moving HQ close to front line, increase happiness, building COC.

I'm doing all that and it barely helps. I play most of my games with Fundamentalism, I expand equally into all sides so HQ is around center, I fix drones asap with anti-drone buildings. I put sensors everywhere and try my best to play 'catch-a-probe' game. But this works until it doesn't - a single mistake and it's game over instantly.

> Buying bases is a designed counter play against wildly advancing opponent.

In reality it's wildly advancing opponent (transcend AI) that also rushes probes and buying everything he can (as long as probes can reach it). So I have to defend against bigger force with smaller force at all times, and if I fail once it's often a game over.

> This is designed on purpose to outweigh sheer military power.

Transcend AIs have both superior military power AND superior probe number with seemingly infinite buying power.

> Losing a base with large army is not losing the game. One just loses a momentum.

On Transcend it easily is, you won't ever be able to build enough new units to outweight AI's original army PLUS former army of yours that is also moving against you right now, and roads between cities make your other cities reachable in 1-2 turns and captured aswell. By the time you build several units you will lose half of your empire.

> Player may need to switch to defense until they accumulate more attackers.

The only 'defence' against probes is building more probes, so if you didn't build enough in advance there is nothing you can do, no army or fortifications will make any difference.

> One need to have strong economy to fuel conquest.

It's impossible to have stronger economy than transcend AI, try it. Transcend AI is to be beaten by smaller force, but superior strategy, but in reality it turns into 'who can build more probes' (where player can't win) and 'dont let a single probe in' (which works until it doesn't and then it's game over0.

> From the other side being economically weaker and hoping to lead unstoppable conquest is an illusion

It actually works (and is the only way to play vs transcend AI), as long as random probe doesn't sneak in and buy my entire army. In my games 49 of 50 lost cities are due to mind control probes and not military conquest.

Or are you saying Transcend difficulty is supposed to be unbeatable? Guaranteed loss?

> Can you share your save?
That one was lost, but I enabled autosaves for my current game.

**Comment by tnevolin** [comment]
> In the field only lone units are purchasable, and it looks like it was intentional. Cities, however, can be purchased instantly with everything inside, how does it make sense?

It is changed in this mod. Now even stacked units are purchasable as well.

Regarding units in MC base it would not make much sense if enemy units still active in it and around. I guess this is pretty normal solution.

> I'm doing all that and it barely helps. I play most of my games with Fundamentalism, I expand equally into all sides so HQ is around center, I fix drones asap with anti-drone buildings. I put sensors everywhere and try my best to play 'catch-a-probe' game. But this works until it doesn't - a single mistake and it's game over instantly.

I guess everybody would share same feeling me included. In vanilla it is even worse as there units are not part of the MC cost.

Feel free to propose a solution. Disabling MC is one. However, a better one would keep MC around with some reasonable usage of it.

> ... shortening your comments about how nothing works on Transcend ...

I don't want to offend your feelings and I am not discarding your requests. However, look at this from a normal game industry point of view. Not from your vast experience playing Civ1 - Civ2 - SMACX where AI really sucks to the point that even hardest difficulty is a cakewalk.

From normal game design point of view hardest difficulty should be hard to the level next to impossible to win. That is for super seasoned player with all exploits and verified strategy and with all the luck combined. It would require an enormous amount of especially detailed micromanagement to even bent game toward you. And even then one can lose quite often. That masochistic level is there for purpose to set a proper difficulty scale. So that everybody can pick a most comfortable one.

Why on Earth would you insist on making game easier to match vanilla difficulty levels? Have you read [this](https://github.com/tnevolin/thinker-doer#difficulty-warning) explicit warning? This mod (with Thinker embedded) makes it more difficult **by design** to give people **more** challenge they asked for. Try easier level if you cannot beat this one. There is no shame in it as Vanilla Transcend = WTP Librarian. In fact, a lot of seasoned player who playtest it cannot win on Transcend. You are not alone there.

> > From the other side being economically weaker and hoping to lead unstoppable conquest is an illusion
> 
> It actually works (and is the only way to play vs transcend AI), as long as random probe doesn't sneak in and buys my entire army. In my games 49 of 50 lost cities are due to mind control probes and not military conquest.

You mean your can build and set in motion undead army in WTP capable to conquer whole world without major losses? Forgive me my disbelief but it doesn't sound right. Yes. This was a winning strategy in vanilla but I think I seriously nerfed it in this mod. Even if I can pull it off periodically it becomes harder and harder to advance as more factions start hating you.

Nevertheless. If you can constantly pull this trick please send me saves (preferably throughout the whole game). Then we may need to tune it a little more. This is work in progress.

Thank you for your playtesting!

**Comment by tnevolin** [comment]
https://github.com/tnevolin/thinker-doer/releases/tag/246

I don't know how to stop AI from MC. I just added another parameter that proportionally increases subversion and mind control cost. I have set it to 5 now. You can crank it up higher to make it even more difficult for AI to buy bases.

This is for testing purposes. I will return it to 1 in later versions. I hope someone will propose some more acceptable solution.
