### ISSUE TITLE
Combat random range is too extreme

### ISSUE THREAD

**Issue by afwbkbc** [tnevolin/thinker-doer#78]
It feels like Combat Strength is useless now, I've had missile rovers dying while attacking formers, 1-3-1 defending vs 12-1-2 successfully, same with ships too, it's almost impossible to predict who will win, it becomes a sort of roulette.
Again, see this game from yesterday - https://www.youtube.com/watch?v=XPH0-oMPmBk - and more often than not combat resolved in a way that should be exception, not a common occurence.
Some random should exist but no way do I have to bring SEVERAL missile rovers to kill one former (just in case former somehow defeats first).

Please make it less random, in Vanilla the range was perfect.

p.s. oh, and Psi combat is actual roulette (like 50/50), regardless of morale / boil size etc, one needs high LUCK to be able to successfully rely on worm army. It was a bit like that in Vanilla too, but now it's worse. It's not unusual for one worm to kill several trance scout patrols or empath rovers and then eat city aswell (just because bad luck). I liked that 3:2 in Vanilla, since it allowed to employ actual strategies, defending funguses with small group of worms (and Isle of the Deep was annoying because of 1:1, every attack could be a suicide, now it's same with land worms aswell).

**Comment by tnevolin** [comment]
> Some random should exist but no way do I have to bring SEVERAL missile rovers to kill one former

This topic was discussed like a hundreds of times already. Please read previous discussions about amount of randomness in the forum thread. A lot of smart people have already expressed a lot of smart opinions. Please capitalize on their wisdom. Alternatively you can renew this discussion on a forum. This is too much of a deal to qualify as a single issue.

There are plenty of player with opposite point of view. See if you can persuade them first. I am relatively neutral to it.

See alternative_combat_mechanics_loss_divisor=2.0 property in thinker.ini. Setting it to 1.0 reverts randomness to vanilla.

> more often than not combat resolved in a way that should be exception, not a common occurence

Are you saying winning percentage is not close to what odds dialog displays? Please send me the save where you were testing that and test results.

The way you worded it I take it you actually did not test the same combat outcomes at least 100 times. As much as I appreciate feedback there is certain math scrutiny about testing randomness. No offense but there are plenty people around not understanding what probability is and what it should be eaten with. There is no use to discuss probability in "common sense" terms.

> Psi combat is actual roulette
> It's not unusual for one worm to kill several trance scout patrols or empath rovers and then eat city aswell (just because bad luck).

I didn't get what it is about. A big part of it sounds like complain against vanilla rules. How 3:2 odds help you defending fungus with worms if they get beaten more badly? Please be specific.

No. It is not unusual to get beaten just because of bad luck. I don't see much problem with that. Have you ever played poker?


# Generic comment

This is a mod. And as any mod it may play somewhat different from vanilla and other mods, obviously. I take it you didn't play it before much. Please try to get use to it and find winning strategy before criticizing it on a ground that it differs from vanilla (or some other mod). You understand I am quite aware of that myself and such feedback alone won't have any effect?
😉

**Comment by afwbkbc** [comment]
> Are you saying winning percentage is not close to what odds dialog displays?
maybe in 100 combats it will be close, but in smac every fight can be critical (for example, I have my last 8-1-2 rover that hasn't moved vs his last 1-3-1 with 50% health in city (and next turn he'll build another sentinel), then I attack and despite strength like 8 vs 3 (and his sentinel damaged) my rover dies instead, this is a bit annoying - well-planned strategies fail because of random.
Yes I do play poker but I play poker to play poker and play smac to play smac :) Smac is where strategies should be able to be planned (i.e. 'I will take X units against their Y units because strength will be 2x greater on average'), instead of gambling ('I will hit them with units until I get lucky').
Well, for now I don't take chances and just bombard everything to 50% or less hp before actually attacking, but once they get artilleries too the problem returns.
Oh, and bigger problem is defending own bases that are in distant locations. How many sentinels do I need there? In vanilla one + perimeter would be guaranteed to hold for enough time (against small armies and worms) for reinforcements to arrive, now one sentinel can die to something with 3x less combat strength, so I need 2 just in case? But if I'm unlucky twice these 2 can die aswell (and they eat support too so can't just spam tons). It's even worse with probes since it's nearly 50/50 odds regardless of morale (I've tried defending with Elite probes and they still died to Hardened and even Disciplined very often).
And yes Morale loses purpose a bit, because 1) it's hard to get somebody to Elite level 2) it doesn't get much of it and can die to Hardened/Disciplined often.
Yes it evens up in big numbers, but as your empire grows bigger you will need to split armies to many smaller parts (especially when placing defence at bases), and any small army can fail against all odds just because of bad luck.

> How 3:2 odds help you defending fungus with worms if they get beaten more badly?
because I would attack with worms first or hide somewhere where they can't be attacked.

**Comment by tnevolin** [comment]
Main thread: https://alphacentauri2.info/index.php?topic=21359.0
Don't remember where in it exactly. Probably somewhere in first half.

This one seems on the topic too.
https://alphacentauri2.info/index.php?topic=21371.0

This one is pretty old. Not sure about it.
https://alphacentauri2.info/index.php?topic=21129.0

And this one is just ancient.
https://alphacentauri2.info/index.php?topic=21046.0

Check the video in this post too.
https://alphacentauri2.info/index.php?topic=21371.msg122882#msg122882


TBH a lot of people complain about excessive randomness. Not all of them, though.
I gave an example of poker because it is not a roulette. It has a lot of randomness in it but it also has strategy. There are more and less experienced players participating in championships. There are no championships in roulette. Chess are on the other side of the spectrum with no randomness whatsoever. Computers games traditionally have randomness embedded by design. In this regard Civ1 is a classic one with a regular amount of randomness as in pretty much all other dice board games. Whereas Civ2/SMACX is a huge step toward chess where randomness is cut in about 10 times comparing to Civ1.

I do not really understand what this randomness fuss is about. It sure makes outcomes less predictive and makes human life harder by making different strategies more complicated to weight in head. On the other side, it makes life of game designer much easier as it does not require deep turn analysis and allows great amount of slack. With randomness even stupid AI can beat inexperienced human by sheer massive production.

What is the alternative? Make it more deterministic chess like? That would require building a really chess like computer algorithms. Do you have any idea how much it cost to build Deep Blue? Don't expect to have such sophistication in $15 game.

I have asked this question here and will on the thread too. Will see what people say.
https://www.reddit.com/r/4Xgaming/comments/naqwbi/randomness_in_smacx_or_other_games/
https://www.reddit.com/r/alphacentauri/comments/naqx4p/randomness_in_smacx_or_other_games/

**Comment by afwbkbc** [comment]
Well actually I'd prefer smac to be more like chess (but still with _some_ randomness) than like poker, because it has great depth of mechanics and possible strategies, which become nullified by randomness (anything can just don't work for no reason), so game becomes a sort of gambling where lucky inexperienced player can beat expierienced one that was unlucky. And no, no amount of experience can compensate for bad luck with that range (when your missile rover can die attacking enemy former for no reason, or random worm can eat half of your army and couple of bases).
Big amount of randomness is more friendly to inexperienced players because it evens up the odds, but smac is not some hypercasual game like Happy Farm, it's more like chess, yes, always was and should be imo.
Oh, and vs Transcend AI big random factor makes winning nearly impossible (since you can't employ "beat large numbers with few" strategies reliably, and this is your only choice).

**Comment by afwbkbc** [comment]
Ahhh, but let's compare it to poker, why not.

POKER: Every game is short, very short. So one can play hundreds and thousands of them every day. Yes, lucky inexperienced player can beat unlucky experienced player in one game, but over time experienced players will get out winners by better risk/reward managing.
SMAC: Every game can last day, days, or week. So lucky inexperienced players can beat unlucky experienced players long enough for latter to just give up (they won't be able or want to play thousands of games to be able to finally win).

POKER: Every game is insignificant, so losing one or even multiple games in a row due to bad luck is no big deal.
SMAC: Every game is long and requires maximum effort to be put into, so losing it due to sudden bad luck ("random worms came and eaten all defenders on important base with many important secret projects that was under siege by enemy, so it got captured by enemy for free and they got secret projects and snowballed from there", "random spore launcher spawned and bombarded all mines/boreholes while killing any unit that tried to attack it, ruining base's industry and failing to complete important project faster than opponent did" (real story this one), etc). Having one bad luck annihilating all your effort is extremely frustrating and stomps your desire to play another game. Even worse - it will make lucky opponent look like he won by skill, and if you even try to tell about luck you will be bashed as 'git gud' or 'learn to lose like a man', by less experienced player (can you imagine that after losing poker game? I can't). So of course inexperienced players would LOVE huge random factor, because how else they can win? Of course they will beg for that on forums etc.

But hey, maybe 1 poker game = 1 smac battle? Well, not really.
POKER: every game is of equal importance to whole 'career'. You lose some, you win some, no big deal.
SMAC: some battles are really critical, such as defending important base, preventing enemy from completing important project, protecting airport where your planet buster was just moved, etc. SMAC is a game of many sharp strategic possibilities. So bad luck that happened 'in right place in right time' can lead to game over for you. And the only way to defend against unexpected bad luck is by stuffing extra units everywhere, something that will lead to defeat aswell (since opponent can use same resources for empire development instead).

POKER: player can decide risk/reward of every game flexibly.
SMAC: player have a bit of risk/reward decisions, but flexibility is non-existent, for example once you built base somewhere and then built important project on it you won't be able to undo or move it or modify how much you will lose if it's taken.

So, as you see, poker is a game _built around risk/reward management long-term_, that's why big amount of luck is acceptable (and even beneficial) there. Smac is a slow, long game of well-thoughts decisions, with near-zero ways to even up 'bad luck' that happened in critical place, so throwing big amounts of random into it makes skilled players equals of green newbies, and whole 'well-thought' aspect loses purpose, since you can never know where and when impossible 'bad luck' will happen and cost you game (and 'bad lucks' like these happen a lot currently).

**Comment by tnevolin** [comment]
Very well put. You have a point. I will think about making it behave closer to vanilla in next releases.
Do you have a name on AC forum or in reddit?

**Comment by afwbkbc** [comment]
Thanks for understanding :)
And no, don't have time to participates in forums/reddits much, but we have our small multiplayer smac (other games) community in jabber at conference@bitcheese.net, you can find me there usually.

**Comment by tnevolin** [comment]
Jabber? Never used it. Any good PC clients for it?

**Comment by tnevolin** [comment]
Let me show you a flip side of predictive combat. Vanilla is a good example with pretty tight range of random combat. When it goes beyond 2:1 range it is almost sure kill (=14:1 winning odds). That does make it pretty chess like if you played a lot of vanilla. However, if you look at the range of available combat bonuses and some average spread on weapon/armor research you'll see that they are: 25%, 50%, 100%, 200% (PD+TF). Taking in account different advance in research there will be also some 25-50% variance in available weapon/armor. Plus damage. Plus artillery. The combinations of above factors push strength ratios beyond 3:2 (almost always) - 2:1 (quite often) - 3:1 (not uncommon). As a result, it is quite possible to build impenetrable defense beyond PD+TF or sometimes an unstoppable assault forces with sizeable advance in technology.

That is too much of an advantage against AI who does not know how to break solid defense with artillery and concentrated simultaneous attack. Thinker AI is getting there but not exactly there yet. This deterministic combat is a human advantage as you correctly stated. I am just concerned if it is too much disadvantage for AI that they won't even be able to break AI to AI defense after that. We'll see.

**Comment by Voker57** [comment]
> That is too much of an advantage against AI who does not know how to break solid defense with artillery and concentrated simultaneous attack. Thinker AI is getting there but not exactly there yet. This deterministic combat is a human advantage as you correctly stated. I am just concerned if it is too much disadvantage for AI that they won't even be able to break AI to AI defense after that. We'll see.

I think it's better to compensate AI shortcomings with AI bonuses. This way, if AIs are missing, gameplay is not affected. Randomizing things leads to more issues.

**Comment by tnevolin** [comment]
235
