### ISSUE TITLE
wrong Cultist faction description

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#90]
They do not have an INDUSTRY penalty.

**Comment by tnevolin** [comment]
Well, maybe it is worth giving it back? Especially based on your overpowered speech in other issue.

**Comment by bvanevery** [comment]
I'm not the best person to comment on fiddling INDUSTRY because in my own work, I don't allow INDUSTRY to be changed around.  Only the Drones have a +1 INDUSTRY bonus, that's it.  No SE bonuses and no faction has any penalties.

**Comment by tnevolin** [comment]
SE is a pretty volatile thing that is impossible to balance. There are some pretty rare cases with obvious over/under powered combinations but other than that it is just a gamble that allows player to explore some combinations. They all can shine in some scenarios but not in others and it is difficult to tell whether one is clearly better. I would revert it to original settings unless people start complaining about them en masse.

Out of my experience I recall just few stand out cases.

Aquatic faction free mineral. That was obviously overpowered and is fixed.

Fungboy sucked all the time against other AI. That was because of them missing extra colony bug and is fixed.

Alien factions possessing noticeable combined power in different bonuses. They are supposed to nullify each other in endless war but when they don't (separated or just one alien in game) they stumped others easily. That is also fixed. Even though it is still kind of borderline I agree for that fix.

Everything else is pretty much minor. Could be fixed or could not - it would not change a balance between AIs. As for human playing certain factions and exploiting their bonuses I don't even bother. People can exploit and abuse every single combination. That is fun of the game.

Let me reiterate it. I don't want to go into fine tuning every faction and, especially, them against each other. It takes a lot of time to gather relevant statistics. I suggest you post your propositions on forum/reddit and we can get back to it when you solicit enough positive feedback.

**Comment by bvanevery** [comment]
> SE is a pretty volatile thing that is impossible to balance. 

I don't agree.  I think you went in a design direction of volatility, which makes _your_ SE more difficult to balance.

 > I suggest you post your propositions on forum/reddit and we can get back to it when you solicit enough positive feedback.

I think you're missing something fundamental here.  People aren't beating down your door to give you precise, high quality, actionable feedback.  Even if I wanted to organize this sort of thing on your behalf, and I don't, it wouldn't happen.  If you need to see an awful lot of democratic votes in order to take action on parts of your project, because you are otherwise burnt out and can't induce yourself to care about certain areas of it anymore, that's simply never going to happen.

If you want to start discussions to get design feedback, do so.  At the end of the day it is your project.  I've done piles of playtesting work already and do not feel a need to belabor my conclusions with additional hours of committee discussion, that isn't going to happen in the real world anyways.

**Comment by tnevolin** [comment]
No. They are not. I guess the time of SMACX has passed. I should develop it 10 years ago.
😃😒

Still want to ask for that if I have an option. At least this will make my thoughts straighter.

**Comment by bvanevery** [comment]
Yes we would have been better off doing our work 10 years ago, but we didn't.  At least I learned many things about the fully loaded costs of producing a commercially viable 4X game.  So I may yet spit out a new one.

**Comment by tnevolin** [comment]
I gave them industry penalty back and some other penalty too. At least this issue could be closed.
