### ISSUE TITLE
remove POLICE and WORMPOLICE abilities from factions

### ISSUE THREAD

**Issue by bvanevery** [tnevolin/thinker-doer#91]
The Spartans are seriously overpowered because Speeders are cheap as dirt in WTP, plus they have +1 POLICE which lets them easily get to +3 POLICE when choosing Police State.  This lets all their units do 2x police duty as though they all had Non-Lethal Methods.  The Cult of Planet is overpowered with +2 PLANET easy mindworm stomping, and similarly has WORMPOLICE, as though all their easily captured mindworms had Non-Lethal Methods.  As it has been the policy of your mod to restrict the use of police, don't allow these factions to have them.  If they were weak factions that didn't have any other advantage, that would be different, but they're already overpowered factions, with tremendous immediate offensive and exploration capabilities.

I don't have the issue in my mod because I went totally the opposite direction on Non-Lethal Methods.  It's allowed very early and it's baked into the design, as far as how everything is going to grow and be made happy.  +3 POLICE is Yang's schtick in my mod.  Everyone else has to get the Ascetic Virtues or wait for Thought Control.

**Comment by tnevolin** [comment]
Faction are designed to be different to use their good and bad sides. There is no fun to flatten them all out. Besides, this is not a mod for that.
I tend to be very conservative on faction customization and do it only when they obviously get ahead all the time. The only example I recall so far is Pirates aqua minerals which makes them first or second always. Other than that I don't see anyone else beating others to death all the time.

Please create a topic and try to persuade at least few people with your ideas. Then we can introduce them. Otherwise, doing and reverting consumes too much time.

Below is a sample argument. You don't need to respond to them. I am just showing how others may react to it.

+3 POLICE is a great advantage but one need to discover Police State first and then it becomes less beneficial with time. So they can effectively use it like 30-50% of the game probably. Whereas their industry disadvantage is permanent.

Same argument regarding Cult of planet. They got worm army but other than that they got nothing. Worms are not cut through weapon against scout patrols. It is pretty easy to stop them with dedication.

**Comment by bvanevery** [comment]
We're starting to find some basic incompatibilities in our working relationship, such as it is.  I've redrafted this response a number of times, and _here_ is where I think the crux of it lies:

> There is no fun to flatten them all out. 

You do a fair number of things in your mod that are _not fun_.  That are damn tedious actually.  I've yet to finish a single game, in all this playtesting time I've put into it.  Heck I don't think I've even made it into late game, that's how bad it is.  You have sucked the fun out of so many things, putting them on such tight tedious budgets... that it may be your total _slop_ with the factions, is the only tool you have for bringing the fun back.

There's only so many times I'm going to tell you what's obviously wrong, before I stop.  **You need to balance your factions.**  If you're not willing to do that, and instead see choosing a faction as some kind of de facto "difficulty selection", or easy / hard play style challenge, well I don't see that a committee discussion is going to change anything.

**Comment by tnevolin** [comment]
> You do a fair number of things in your mod that are _not fun_

Agree. Everybody has different definition of fun. I realize that it is impossible to satisfy everybody so I just follow my gut on what entails fun to me. Specifically, this is some play style that involve managing multiple aspect of the game and even abusing certain aspects but not to the level when such abuse completely overrides other aspects of the game. It comparative parlance I prefer it resemble chess it the way where every singe turn matters and it take great deal of thinking to get synergy of all your pieces working together. Any huge mistake or oversight cannot be saved by applying some single use wunderwaffe. Winning is the result of multiple steps where each should be taken to the best even exploiting and abusing if needed but not disregarding. Constant attention and concentration for 400 turns in a row. That is my definition of fun.

So I am eliminating elements allowing people win with a single turn, exploit, wonder, etc. That is definitely cutting fun for those wunderwaffe lovers.

I am surprised I need to reiterate it to you since you should be pretty familiar with this mod and know its motto and principle.

Returning to factions. I don't mind to balance them. I am just thinking they are pretty much balanced already. So far you didn't prove me wrong.

**Comment by bvanevery** [comment]
> So I am eliminating elements allowing people win with a single turn, exploit, wonder, etc. That is definitely cutting fun for those wunderwaffe lovers.

You eliminating Non-Lethal Methods for most (all?) of the game, and then giving 2 already strong factions a trivial workaround for that on Turn 1, is cognitive dissonance with your stated design intent. 

>I am just thinking they are pretty much balanced already. So far you didn't persuaded me otherwise.

When is the last time you actually played a full game with either the Cult or the Spartans?  It better be in the last 2 months, or I'm going to say, you aren't **dogfeeding** your own work.

**Comment by tnevolin** [comment]
Non-Lethal Methods are on top of +3 POLICE. They are not substitute.
I also don't see you point. You are saying we need to introduce NLM at turn one just because someone can get to +3 POLICE? That is Reductio ad absurdum. This way you can extend it to "if someone can set +1 POLICE let's disable drone riots for everybody to make it fair".

Maybe I am not dogfeeding my own work. So I may miss a need for some faction to get balanced. Still I need to get to this point to understand it if I don't understand yet.

**Comment by bvanevery** [comment]
Let's take it from the top.  You banished Non-Lethal Methods far as I can tell.  I have yet to play any game where I've gained it.  So if it's in there at all, it's late game.  It is not actionably useful in most of the game.

There are only 3 ways to get a police unit that's 2x as effective as a regular military unit, before the late game:

- a Battle Ogre
- a Cultist mindworm
- getting a +3 POLICE rating

There are only 2 ways to do the latter:
- Be the Spartans and learn the Police State.  Doesn't take all that long, early midgame at worst.
- Build the Ascetic Virtues.  Takes forever to discover and then build.  Late midgame at best.  AI factions may definitely build it before you ever have the chance.

The Cultists and Spartans are both powerful factions already.  They are being made overpowered by this easy happiness.

Cultist overpowering is available on Turn 1.  Yes you have to go capture your mindworms at first, but with a +2 PLANET rating, that's actually easy to do.  It seems to be the threshold at which traditional "sweeping the fungus" strategies ala the original game, work just fine.  +1 PLANET is a bitter pill of watching your newly captured mindworms get themselves killed, if you try to do the traditional sweep.  This is surely due to your +15% increments for psi bonus on both offense and defense.

Spartan overpowering is available early midgame.  Doesn't take that long to learn Police State, particularly when you trade with AI factions that are rather carefree about techs they'll release to you.

**Comment by tnevolin** [comment]
I understand how they get this. No need to explain. I just don't think that this is so overpowered these faction become a no brainer to win.
One need bases to be 7+ (beyond RC, HT, + 3 police units) to cash on this bonus and one need to run PS constantly to cash on this bonus. This is seriously middle game and at this point onward PS kind of loses its value. Meaning some other choices are better. In fact at this point with extended infrastructure it is very cheap to use Psych for drones.
Again this is powerful feature but it does not come for free. Direct bonus to production, for example may be comparable to it.

I'll play them to see how it goes.

**Comment by tnevolin** [comment]
How about a compromise? These abilities are unique and very suitable to these factions lore. What if we add some more penalties to them instead?

**Comment by tnevolin** [comment]
Let me know if this is not sufficient and reopen the case.
